import uuid
from django.db import models

# Use this once we want to keep id the same between Threads and Posts
# https://stackoverflow.com/questions/8950010/django-model-auto-increment-primary-key-based-on-foreign-key


class Thread(models.Model):
    creation_datetime = models.DateField(auto_now_add=True)
    id = models.AutoField(primary_key=True)

    # From User
    email = models.EmailField(null=True)
    topic = models.CharField(max_length=100, null=True)
    text = models.TextField(max_length=6000)
    file = models.FileField(upload_to='uploads/%Y/%m/%d/', null=True)
    hide_file = models.BooleanField(default=False)
    embed = models.URLField(null=True)

    # To remove thread, use autogenerated password
    password = models.UUIDField(default=uuid.uuid4, editable=False)


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    creation_datetime = models.DateField(auto_now_add=True)
    id = models.AutoField(primary_key=True)

    # From User
    email = models.EmailField(null=True)
    topic = models.CharField(max_length=100, null=True)
    text = models.TextField(max_length=6000)
    file = models.FileField(upload_to='uploads/%Y/%m/%d/', null=True)
    hide_file = models.BooleanField(default=False)
    embed = models.URLField(null=True)
    is_op = models.BooleanField(default=False)

    # To remove a post, use autogenerated password
    password = models.UUIDField(default=uuid.uuid4, editable=False)
