# Generated by Django 3.0.6 on 2020-05-23 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('creation_datetime', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=6000)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('hide_file', models.BooleanField(default=False)),
                ('embed', models.URLField()),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('creation_datetime', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=6000)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('hide_file', models.BooleanField(default=False)),
                ('embed', models.URLField()),
                ('is_op', models.BooleanField(default=False)),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Thread')),
            ],
        ),
    ]
