# Generated by Django 3.0.6 on 2020-05-24 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_datetime', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(max_length=6000)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('hide_file', models.BooleanField(default=False)),
                ('embed', models.URLField(blank=True, null=True)),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.Entry')),
            ],
            bases=('boards.entry',),
        ),
        migrations.CreateModel(
            name='PostEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boards.Entry')),
                ('is_op', models.BooleanField(blank=True, default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.ThreadEntry')),
            ],
            bases=('boards.entry',),
        ),
    ]
