# Generated by Django 3.0.7 on 2020-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200812_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
