# Generated by Django 3.0.7 on 2020-08-12 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200812_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='password',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
